name: Deploy to Kubernetes Cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME: jojodocker10/laravel-application
  IMAGE_TAG: latest
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}

jobs:
  test-laravel-app:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5:7

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install and setup laravel dependencies
      run: |
        cat ${{ secrets.ENV_FILE }} > .env.example
        bash laravel_test.sh
      working-directory: laravel-app

